# Content for the Forensic Manual (Help > Forensic Manual)

MANUAL_TEXT = """
DOCRECON FIELD MANUAL: INTERPRETING YOUR RESULTS
============================================================

This guide explains the forensic findings generated by DocRecon.
Use this to understand the "Red Flags" and the hidden history of your documents.

1. GENEALOGY & BATCH ANALYSIS (Tools > Genealogy Scan)
------------------------------------------------------------
This tool scans an entire folder (and subfolders) to find "Family Trees" of documents.
It compares the "DNA" (RSIDs) of every file against every other file to see if they are related.

• GROUP 1: HIGH CONFIDENCE MATCH (>90%)
  Verdict: CLONES / COPIES.
  These files are virtually identical in their editing history.
  - Likely Scenario: The user copied "Report_v1.docx", renamed it "Report_Final.docx", and made tiny changes.
  - Forensic Value: Proves that File B is a direct descendant of File A.

• GROUP 2: PARTIAL MATCH (<90%)
  Verdict: SHARED ANCESTOR.
  These files share a significant amount of history but have diverged.
  - Likely Scenario: Two different employees started with the same "Q3_Template.docx" but wrote different reports. They share the "Template DNA" but have different "Content DNA".
  - Forensic Value: Links disparate documents back to a common source or organization.

• GROUP 3: ISOLATED
  Verdict: UNIQUE / UNRELATED.
  These files share NO editing history with the others.
  - Forensic Value: If you are investigating a specific leak, "Isolated" files might be irrelevant or from a completely different source.

2. RSID "GHOSTS" (The "Authors & History" Tab)
------------------------------------------------------------
An RSID (Revision Save ID) is a digital stamp Word applies every time you hit 'Save'.

• WHAT IS A "GHOST"?
  A user who appears in the file's "Save History" (Metadata) but does NOT own any text in the visible document.

• WHAT DOES IT MEAN?
  1. The Viewer: They opened the file, read it, and saved it without typing.
  2. The Deleter: They wrote text, saved it, but that text was deleted by someone else later. Their "Save ID" remains, but their text is gone.
  3. The Corrector: They only fixed minor typos (like changing "teh" to "the"). Word often preserves the original author's stamp on the paragraph, turning the corrector into a "Ghost".

3. EDITING VELOCITY (The "Metadata" Tab)
------------------------------------------------------------
We calculate the "Humanity" of the document by comparing "Edit Time" vs. "Word Count".

• IMPOSSIBLE VELOCITY (> 500 words in < 1 minute)
  Verdict: SYNTHETIC / PASTED.
  Humans cannot type this fast. The text was likely generated by AI (ChatGPT) or copied from a PDF/Webpage and pasted in bulk.

• HIGH VELOCITY (> 150 Words Per Minute)
  Verdict: SUSPICIOUS.
  Professional typists hit ~80 WPM. Speeds above 150 suggest heavy copy-pasting or automated generation.

• LOW VELOCITY (< 5 Words Per Minute)
  Verdict: ORGANIC / HUMAN.
  Normal for high-value documents. Indicates the author spent time reading, thinking, and reviewing.

4. ORIGIN VERDICTS (The "Origin" Tab)
------------------------------------------------------------
• ORGANIC:
  Created by a human in Microsoft Word. The internal structure is messy and natural.

• SYNTHETIC / GENERATED:
  Created by software (PDF converter, Python script, or Google Docs export).
  Why? Software creates perfect, sequential IDs (1, 2, 3...). Humans create chaos (1, 5, 2, 9...).

• WASHED / HYBRID:
  A file that started as Synthetic (e.g., Google Docs) but was opened and re-saved in Word.
  This "washes" away some evidence, but DocRecon detects the mismatch between the file's age and its history length.

5. HIDDEN THREATS (The "Deep Artifacts" Tab)
------------------------------------------------------------
• MACRO (VBA) STOMPING
  Standard .docx files should NEVER contain code.
  If DocRecon finds "vbaProject.bin" inside a .docx, it is a high-confidence malware indicator. The attacker changed the extension to hide the virus.

• WHITE TEXT
  - Harmless: White text on a blue textbox or dark header.
  - Suspicious: White text on a white background. Used to hide keywords (to trick search engines) or malicious links (to trick users).

6. METADATA & "TEMPLATE INHERITANCE"
------------------------------------------------------------
• WHY IS THE AUTHOR WRONG?
  If "Henriette" creates a Template, and "Rasmus" opens it to write a report, the internal "Creator" field often still says "Henriette".

• HOW TO READ IT:
  - Creator: The person who made the blank file/template.
  - Last Modified By: The person who finished the work.
  - Timeline: DocRecon attempts to link the specific RSIDs to these people to show who did what.

7. MEDIA & EXIF (Location Data)
------------------------------------------------------------
• GPS COORDINATES
  If a user inserts a photo from a smartphone, the GPS location might be hidden inside the document.
  DocRecon extracts this to show you exactly where the photographer was standing.

• CAMERA / SOFTWARE
  Can reveal if an image was edited in Photoshop before being inserted, or if it came from a specific phone model (e.g., "iPhone 13 Pro").
"""